filesystem-cleanup: Add parameter to show changes
Use --dry-run to only show files that would be deleted, but do
not actually delete them.

Signed-off-by: Daniel Weismüller <daniel.weismueller@ipfire.org>
Signed-off-by: Arne Fitzenreiter <arne_f@ipfire.org>

diff --git a/src/scripts/filesystem-cleanup b/src/scripts/filesystem-cleanup
--- a/src/scripts/filesystem-cleanup
+++ b/src/scripts/filesystem-cleanup
@@ -27,6 +27,22 @@ PATHS=(
 )
 
 main() {
+	local dry_run="false"
+
+	while [ $# -gt 0 ]; do
+		case "${1}" in
+			--dry-run)
+				dry_run="true"
+				;;
+
+			*)
+				echo "${0}: Invalid argument: ${1}" >&2
+				return 2
+				;;
+		esac
+		shift
+	done
+
 	# Update the runtime linker cache (this may fix any broken symlinks)
 	ldconfig
 
@@ -65,7 +81,12 @@ main() {
 						;;
 
 					*)
-						unlink "${file}"
+						echo "Removing ${file}..."
+
+						# Actually remove the file (maybe)
+						if [ "${dry_run}" = "false" ]; then
+							unlink "${file}"
+						fi
 						;;
 				esac
 			done
